### ISSUE TITLE
Install failure: repository has no Release file

### ISSUE THREAD

**Issue by Talldad** [adrianiainlam/indicator-keyboard-led#5]
Having trouble installing; receive this error from apt update:
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/adrianiainlam/indicator-keyboard-led/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely and is therefore disabled by default.
 
Using Ubuntu 20.04 LTS
Regards,
Talldad

**Comment by adrianiainlam** [comment]
Hi,
This is because I haven't built the package for Focal yet.
I'll do it later today, please try again tomorrow.

**Comment by adrianiainlam** [comment]
I have just published a package for Focal. I haven't actually tested it though - I was aware it may not work on Xubuntu 18.10 (see issue #3) so I'm not sure how well it will work on Focal. Feel free to try it out and report back, or (if I have time later tonight) I will set up a VM to test it.

**Comment by adrianiainlam** [comment]
Just tried this on a Focal VM, seems to be working fine so closing issue. If you experience any problems please reopen.

A few minor issues and workarounds:

1. You also need to install `gir1.2-appindicator3-0.1`.
2. Depending on your system configurations / fonts / etc, the on/off icons may be shown as "emojis" rather than normal characters, and may cause the icons to look like the on/off states are inverted. If this is the case for you, you can edit line 109 of `/usr/bin/indicator-keyboard-led`. Either swap the two icons in `'⚫' if state else '⚪'`, or change them to other characters that you like.
